from decouple import config

MONGO_DATABASE = config("MONGODB_INITDB_DATABASE")
MONGO_USERNAME = config("MONGO_INITDB_ROOT_USERNAME")
MONGO_PASSWORD = config("MONGO_INITDB_ROOT_PASSWORD")

MONGO_HOST = config("MONGO_HOST")
MONGO_PORT = config("MONGO_PORT")

MONGO_URL = (
    f"mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@" f"{MONGO_HOST}:{MONGO_PORT}/{MONGO_DATABASE}?authSource=admin"
)
