version: "3.8"

services:
    mongo:
        image: mongo:5.0.2
        restart: always
        volumes:
            - mongodata:/data/db
            - ./backend/docker/mongo:/docker-entrypoint-initdb.d
        ports:
            - 27017:27017
        env_file: ./config/.env
        container_name: flopphouse_mongo

    backend:
        build:
            context: ./backend
            dockerfile: docker/python/Dockerfile
        env_file: ./config/.env
        container_name: flopphouse_backend
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - mongo
        volumes:
            - ./backend:/backend

volumes:
    mongodata: