from decouple import config

MONGO_DATABASE = config("MONGO_INITDB_DATABASE")
MONGO_USERNAME = config("MONGO_INITDB_ROOT_USERNAME")
MONGO_PASSWORD = config("MONGO_INITDB_ROOT_USERNAME")

MONGO_HOST = config("MONGO_HOST")
MONGO_PORT = config("MONGO_PORT")

MONGO_URL = f"mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}/{MONGO_DATABASE}"
